In [2]:
import jax.numpy as jnp

from bngif.iklp import build_Psi, build_X

ModuleNotFoundError: No module named 'bngif'

In [3]:
import jax

M, P = 6, 4
a = jnp.array([0.8, -0.3])
x = jnp.linspace(1.0, 6.0, M)

Ψ = build_Psi(M, a)
X = build_X(x, P)

print(Ψ)
print(X)


[[ 1.   0.   0.   0.   0.   0. ]
 [-0.8  1.   0.   0.   0.   0. ]
 [ 0.3 -0.8  1.   0.   0.   0. ]
 [ 0.   0.3 -0.8  1.   0.   0. ]
 [ 0.   0.   0.3 -0.8  1.   0. ]
 [ 0.   0.   0.   0.3 -0.8  1. ]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 2. 1. 0.]
 [4. 3. 2. 1.]
 [5. 4. 3. 2.]]
